<?php 
	
$title = 'Patchology&#39;s Moisture Max Out';
		
$description = 'Beauty at the speed of you. Enjoy a skin moisture makeover with a gift package by Patchology. Winner will receive a care package of some of Patchology&#39;s most popular on&#8211;the&#8211;go products.';

$keywords = 'MODERN LUXURY, Beauty, Patchology, Skin, Moisture';

$header = '<i>LET YOUR SKIN DRINK IT IN</i>';

/*$headline = '<i></i>';*/

/*$subheadline = '';*/

$copy = 'Give your face a burst of hydration with these summer skincare essentials from Patchology&#8212;from their best&#8211;selling masks and patches, to their newest lip treatments and cleansing wipes. <span><strong>Valued at &#36;215, we&#39;re giving away 10 sets to 10 lucky winners&#33;</strong></span>';

$copy2 ='';


//$closed = 'THIS CONTEST IS NOW CLOSED.';


/* $termsconditions = '<h1>MODERN LUXURY’S “ULTIMATE GOURMET VIP PACKAGE” SWEEPSTAKES OFFICIAL RULES</h1>
<h2>Official Rules</h2>

<p>A complete copy of these rules can be obtained at the office of Chicago Social Magazine (“Magazine”), owned by DM Luxury, LLC (“Sponsor”), during normal business hours Monday through Friday or by sending a self-addressed, stamped envelope to Sponsor at address below.</p>

<p>Sponsor will conduct the Modern Luxury’s “ULTIMATE GOURMET VIP PACKAGE” Sweepstakes (the “Sweepstakes”) substantially as described in these rules, and by participating, each participant agrees as follows:</p>

<p><strong>NO PURCHASE IS NECESSARY.  A PURCHASE OR PAYMENT OF ANY KIND WILL NOT INCREASE YOUR CHANCES OF WINNING.  VOID WHERE PROHIBITED.  ALL FEDERAL, STATE, AND LOCAL REGULATIONS APPLY.</strong></p>

<ol>

<li><strong>Eligibility:</strong> This Sweepstakes is open only to legal U.S. residents who are age 21 or older at the time of entry and who reside in the forty-eight contiguous United States and the District of Columbia.  Void where prohibited by law.  Employees of the Magazines, Sponsor, its managing partner, affiliates, subsidiaries, promotional sponsors, prize providers, and the immediate family members and household members of such employees are not eligible to participate. The term “immediate family members” includes spouses, parents and step-parents, siblings and step-siblings, and children and stepchildren.  The term “household members” refers to people who share the same residence at least three (3) months out of the year. The Sweepstakes is subject to all applicable federal, state and local laws and regulations. Participation constitutes entrant’s full and unconditional agreement to these Official Rules and Sponsor’s decisions, which are final and binding in all matters related to the Sweepstakes. Winning a prize is contingent upon fulfilling all requirements set forth herein.</li>		

<li><strong>Sweepstakes Period:</strong> The Sweepstakes will begin at 6:00am ET on October 17, 2016 and will run through 11:59pm ET on October 24, 2016 (the “Sweepstakes Period”).  Sponsor’s computer is the official time keeping device for this Sweepstakes.</li>

<li><strong>How to Enter:</strong> You will automatically be entered into the Sweepstakes once you complete the following: Visit the website www.capitalonechicago.modernluxury.com and complete an entry form (each an “Entry Form”).  All entries must be received by 11:59pm ET on October 24, 2016.  Limit one (1) Entry Form per email address during the Sweepstakes Period.  Multiple participants are not permitted to share the same email address. Any attempt by any participant to submit more than one (1) Entry Form by using multiple/different email addresses, identities, registrations and logins, or any other methods will void that participant may be disqualified. Use of any automated system to participate is prohibited and will result in disqualification.  Sponsor is not responsible for lost, late, incomplete, invalid, unintelligible, inappropriate or misdirected registrations, all of which will be disqualified.  In the event of a dispute as to any registration, the authorized account holder of the email address used to register will be deemed to be the participant. The “authorized account holder” is the natural person assigned an email address by an Internet access provider, online service provider or other organization responsible for assigning email addresses for the domain associated with the submitted address.  Potential winner may be required to show proof of being the authorized account holder. All entries become the sole and exclusive property of Sponsor and will not be returned.  Sponsor reserves the right to contact entrants and all other individuals whose email address is submitted as part of this promotion.  No mail-in entries will be accepted.</li>

<li><strong>Winner Selection:</strong>On October 25, 2016, Sponsor will select one (1) entry for the Grand Prize described below in a random drawing of all valid Entry Forms received by Sponsor during the Sweepstakes Period.  All winning entrants will be contacted using the email address and/or telephone number provided with the Entry Form and may be awarded the prize (subject to verification of eligibility and compliance with the terms of these rules).  Sponsor’s decisions as to the administration and operation of the Sweepstakes and the selection of the potential winners is final and binding in all matters related to the Sweepstakes. Failure to respond to the initial verification contact within one (1) day of notification will result in disqualification.</li>

<li><strong>Verification of Potential Winner:</strong>POTENTIAL SWEEPSTAKES WINNERS ARE SUBJECT TO VERIFICATION BY SPONSOR WHOSE DECISIONS ARE FINAL AND BINDING IN ALL MATTERS RELATED TO THE SWEEPSTAKES. Potential winners must continue to comply with all terms and conditions of these Official Rules, and winning is contingent upon fulfilling all requirements. Potential winners will be notified by email and/or telephone call after the date of random drawing.  Potential winners will be required to sign and return to Sponsor, within ten (10) days of the date notice is sent, an affidavit of eligibility and a liability/publicity release (except where prohibited) in order to claim his/her prize, if applicable.  If a potential winner of any prize cannot be contacted, fails to sign and return the affidavit of eligibility and/or the liability/publicity release within the required time period (if applicable), or if the prize or prize notification is returned as undeliverable, potential winner forfeits prize. In the event that a potential winner of a sweepstakes prize is disqualified for any reason, Sponsor may award the applicable prize to an alternate winner by random drawing from among all remaining eligible entries. A winner who accepts a prize cannot rescind their acceptance and/or return the prize.</li>

<li><strong>Grand Prize:</strong> One (1) winner will be eligible to receive the Grand Prize, which consists of two tickets to a CS Magazine culinary event in October in Chicago IL, and one VIP restaurant experience for two guests to a restaurant featured at this event.  Ground transportation and other expenses not specifically included in the Grand Prize description are the sole responsibility of the winner. ARV of the Grand Prize $400.  Grand Prize is non-transferable.  Winner is responsible for all taxes associated with prize receipt and/or use.  Odds of winning Grand Prize depend on a number of factors including the number of eligible entries received during the Sweepstakes Period.  Sponsor reserves the right to substitute any listed prize for one of equal or greater value for any reason.      

<b><u>Restaurant tasting experience voucher must be used by 12/23/16</u>. Winner and guest must attend both events together. Winner’s guest must be twenty-one (21) years of age or older. Grand Prize is non-transferable and no substitution will be made except as provided herein at the Sponsor’s sole discretion.</b>     </li>

<li><strong>Entry Conditions and Release:</strong> By entering, each participant agrees to: (a) comply with and be bound by these Official Rules and the decisions of the Sponsor, which are binding and final in all matters relating to this Sweepstakes; (b) release and hold harmless the Sponsor, its managing partner, subsidiaries, and affiliated companies, participating sponsors, the prize providers and any other organizations responsible for sponsoring, fulfilling, administering, advertising or promoting the Sweepstakes, and all of their respective past and present officers, directors, employees, agents and representatives (collectively, the “Released Parties”) from and against any and all claims, expenses, and liability, including but not limited to negligence and damages of any kind to persons and property, including but not limited to invasion of privacy (under appropriation, intrusion, public disclosure of private facts, false light in the public eye or other legal theory), defamation, slander, libel, violation of right of publicity, infringement of trademark, copyright or other intellectual property rights, property damage, or death or personal injury arising out of or relating to a participant’s entry, creation of an entry or submission of an entry, participation in the Sweepstakes, acceptance or use or misuse of prize (including any travel or activity related thereto) and/or the broadcast, exploitation or use of entry; and (c) indemnify, defend and hold harmless the Sponsor from and against any and all claims, expenses, and liabilities (including reasonable attorneys’ fees) arising out of or relating to an entrant\'s participation in the Sweepstakes and/or entrant’s acceptance, use, non-use or misuse of the prize. By entering, each participant further agrees to receive marketing communications from Sponsor via any medium, known and unknown. Any participant who opts-out of these communication also remove himself/herself from the Sweepstakes.  By participating in the Sweepstakes, where allowed by law, participants agree that the Sponsor may disclose personal information obtained from participants in the Sweepstakes to third parties and use such information for marketing and other purposes.</li>

<li><strong>Publicity:</strong>Except where prohibited, participation in the Sweepstakes constitutes winner’s consent to Sponsor’s and its agents’ use of winner’s name, likeness, photograph, voice, opinions and/or hometown and state for promotional purposes in any media, worldwide, without further payment or consideration. </li>

<li><strong>Taxes:</strong> All State, Local, Federal and or other taxes, duties, tariffs, title fees, licensing fees, or other fees for prizes awarded become the sole responsibility of the winner.  All those who win a prize or prizes valued $600 or more in any given year will be issued an IRS Form 1099 to report their winnings.</li>

<li><strong>General Conditions:</strong> Sponsor reserves the right to cancel, suspend and/or modify the Sweepstakes, or any part of it, if any fraud, technical failures or any other factor beyond Sponsor’s reasonable control impairs the integrity or proper functioning of the Sweepstakes, as determined by Sponsor in its sole discretion. Sponsor reserves the right in its sole discretion to disqualify any individual it finds to be tampering with the entry process or the operation of the Sweepstakes or to be acting in violation of these Official Rules or any other promotion or in an unsportsmanlike or disruptive manner. Any attempt by any person to deliberately undermine the legitimate operation of the Sweepstakes may be a violation of criminal and civil law, and, should such an attempt be made, Sponsor reserves the right to seek damages from any such person to the fullest extent permitted by law. Sponsor’s failure to enforce any term of these Official Rules shall not constitute a waiver of that provision.</li>

<li><strong>Limitations of Liability:</strong> The Released Parties are not responsible for: (1) any incorrect or inaccurate information, whether caused by entrants, printing errors or by any of the equipment or programming associated with or utilized in the Sweepstakes; (2) technical failures of any kind, including, but not limited to malfunctions, interruptions, or disconnections in phone lines or network hardware or software; (3) unauthorized human intervention in any part of the entry process or the Sweepstakes; (4) technical or human error which may occur in the administration of the Sweepstakes or the processing of entries; or (5) any injury or damage to persons or property which may be caused, directly or indirectly, in whole or in part, from entrant’s participation in the Sweepstakes or receipt or use, non-use or misuse of any prize. If for any reason an entrant’s entry is confirmed to have been erroneously deleted, lost, or otherwise destroyed or corrupted, entrant’s sole remedy is another entry in the Sweepstakes, provided that if it is not possible to award another entry due to discontinuance or completion of the Sweepstakes, or any part of it, for any reason, Sponsor, at its discretion, may elect to hold a random drawing from among all eligible entries received up to the date of discontinuance for any or all of the prizes offered herein. No more than the stated number of prizes will be awarded. In event that production, technical, seeding, programming or any other reasons cause more than stated number of prizes as set forth in these Official Rules to be available and/or claimed, Sponsor reserves the right to award only the stated number of prizes by a random drawing among all legitimate, unawarded, eligible prize claims.</li> 

<li><strong>Disputes:</strong> Entrant agrees that: (i) any and all disputes, claims and causes of action arising out of or connected with this Sweepstakes, or any prizes awarded, other than those concerning the administration of the Sweepstakes or the determination of the winner, shall be resolved individually, without resort to any form of class action; (ii) any and all disputes, claims and causes of action arising out of or connected with this Sweepstakes, or any prizes awarded, shall be resolved exclusively by the United States District Court or the appropriate Georgia State Court located in the City of Atlanta, Georgia; (iii) any and all claims, judgments and awards shall be limited to actual out-of-pocket costs incurred, including costs associated with entering this Sweepstakes, but in no event attorneys’ fees; and (iv) under no circumstances will entrant be permitted to obtain awards for, and entrant hereby waives all rights to claim punitive, incidental and consequential damages and any other damages, other than for actual out-of-pocket expenses, and any and all rights to have damages multiplied or otherwise increased. SOME JURISDICTIONS DO NOT ALLOW THE LIMITATIONS OR EXCLUSION OF LIABILITY FOR INCIDENTAL OR CONSEQUENTIAL DAMAGES, SO THE ABOVE MAY NOT APPLY TO YOU. All issues and questions concerning the construction, validity, interpretation and enforceability of these Official Rules, or the rights and obligations of the entrant and Sponsor in connection with the Promotion, shall be governed by, and construed in accordance with, the laws of the State of Georgia, without giving effect to any choice of law or conflict of law rules (whether of the State of Georgia or any other jurisdiction), which would cause the application of the laws of any jurisdiction other than the State of Georgia.</li>

<li><strong>Entrant\'s Personal Information:</strong> Information collected from entrants is subject to Sponsor\'s Privacy Policy, which is available on every Magazine website under the “Privacy Policy” link. All entry blanks, forms, devices, and materials gathered during the course of entry, as well as all information contained on or within, shall become the sole property of Sponsor to be used, disposed of or destroyed in its sole discretion.  Sponsor is not responsible for any incorrect or inaccurate information entered by website users, and assume no responsibility for any error, omission, interruption, deletion, defect, delay in operation or transmission, communications line failure, theft or destruction or unauthorized access to a Magazine website.      </li>

<li><strong>Sweepstakes Results:</strong> A winners list may be obtained within thirty (30) days after the Sweepstakes Period expires by sending a self-addressed stamped envelope to the Sweepstakes Sponsor identified below.</li>

<li><strong>SWEEPSTAKES SPONSOR:</strong> <strong>DM LUXURY, LLC, 40 Fulton Street, NY NY 10038, Attn: Ashley Stevens “ULTIMATE GOURMET VIP PACKAGE.</strong>  </li>

<li><strong>PRIZE PROVIDER(S):</strong> <strong>DM Luxury, LLC and Capital One</strong></li>

</ol>
';*/

?>